### PR TITLE
added a dashboard to compare stats of different palyers at a time

### PR DESCRIPTION
**Pull request by affaannn**
Linked Issue: 

## Changes
-
-

### CODE REVIEW

**Comment by affaannn** [comment]
Created a dashboard through which we can choose the names of players and stats on which we have to compare the multiple palyers we already coosen at a same time on a bar graph
Screenshot 2023-03-04 171213

**Comment by sbk2k1** [comment]
Hi, @affaannn I would prefer a different folder with the name "prostats.gg" or whatever you decide. Please add different components for a website rather than a single ipynb. HTML file, flask app, and any required artifacts. Also, include a readme on how to set up the website or the endpoint if you decide to deploy it.

**Comment by affaannn** [comment]
> Hi, @affaannn I would prefer a different folder with the name "prostats.gg" or whatever you decide. Please add different components for a website rather than a single ipynb. HTML file, flask app, and any required artifacts. Also, include a readme on how to set up the website or the endpoint if you decide to deploy it.

Okay on it 
And do  I have to create another PR after doing the same ?

**Comment by sbk2k1** [comment]
@affaannn you can commit on this one ig.

**Comment by sbk2k1** [comment]
I'll be closing this PR. Feel free to open this up when needed. Do not make a new one.

**Comment by affaannn** [comment]
> I'll be closing this PR. Feel free to open this up when needed. Do not make a new one.

how can I reopen this PR??

**Comment by sbk2k1** [comment]
You should see the option to reopen down below. If not inform me and I'll open it for you.

**Comment by affaannn** [comment]
> You should see the option to reopen down below. If not inform me and I'll open it for you.

I am not a Contributor that is why I can't see any option for reopening

**Comment by sbk2k1** [comment]
@affaannn just add newer commits to this one then.

**Comment by affaannn** [comment]
> @affaannn just add newer commits to this one then.

added, plzz review it and let me know if it is okay!!

**Comment by sbk2k1** [comment]
Great job @affaannn!

**Pull request merged**
