### PR TITLE
Clustering players based on their playing patterns

### LINKED ISSUE #24: Player Clustering
**Player Clustering:**
Player clustering involves grouping players with similar characteristics together to identify patterns in their performance and behaviour.
To cluster players based on their attributes, we can use clustering algorithms like: _K-means_, _DBSCAN_, _Hierarchical clustering_, _Spectral_ _clustering_ etc.
This can help teams to replace a player with another with similar type of playing patterns/characteristics.

### PR DESCRIPTION
**Pull request by Arg-10**
Fixes #24.
I clustered the players using different clustering algorithms but found K-Means to work the best and proceeded with that to cluster them based on their playing patterns/characteristics.

I plan to work on the issue further and specify probable player roles in a team based on a more detailed clustering.

Our analysis can help teams to find better replacements for their team based on player characteristics/playing patterns by choosing another player in the same cluster.

### CODE REVIEW

**Comment by sbk2k1** [comment]
Hi! @Arg-10 great work! However, can you move the files to the datasets and the notebooks folder with consistent naming?

**Comment by Arg-10** [comment]
Sure! Could you please suggest what names should I give them?

**Comment by sbk2k1** [comment]
@Arg-10 anything that describes what you have done and the artifact produced.

**Comment by Arg-10** [comment]
Sure, will do that ASAP!

**Comment by sbk2k1** [comment]
I'll be closing this PR. Feel free to open this up when needed. Do not make a new one.

**Comment by Arg-10** [comment]
I've made the required changes. 
Please reopen the PR.

**Comment by sbk2k1** [comment]
Thanks, @Arg-10 for the changes.

**Pull request merged**
